"""Add Tags table

Revision ID: dc54c22c875b
Revises: eab4ab24111d
Create Date: 2026-02-11 12:04:40.651740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc54c22c875b'
down_revision: Union[str, Sequence[str], None] = 'eab4ab24111d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booktag')
    op.drop_table('reviews')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('tags_pkey'))
    )
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], name=op.f('reviews_book_uid_fkey')),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name=op.f('reviews_user_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('reviews_pkey'))
    )
    op.create_table('booktag',
    sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], name=op.f('booktag_book_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], name=op.f('booktag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', name=op.f('booktag_pkey'))
    )
    # ### end Alembic commands ###
